# Basic
title: 易水寒秋
subtitle: 一个程序员的博客
welcome_message: <a href="https://yishuihanbaobao.github.io/yishui.github.io/" target="_blank">Download the theme</a>
description: 记录技术成长的点滴!
creator: <a href="https://yishuihanbaobao.github.io/yishui.github.io/">@oyishuihanbaobao</a>

url: "https://yishuihanbaobao.github.io/yishuihanqiu/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://yishuihanbaobao.github.io/yishuihanqiu/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: yishuihanqiu
    # duoshuo: 
    
# Social
#social:
#    weibo: onevcat
#    github: onevcat
#    twitter: onevcat
#    gplus: 107108267983477358170
#    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
